
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("arr is ")
print(arr)
matrix=arr.reshape(3,4)
print("matrix")
print(matrix)
print("single row in matrix")
print(matrix[1])
print("single col in matrix")
print(matrix[:,2])
print("multipilication of matrix with 5")
print(matrix*5)
print("add 10 to every ellement ")
print(matrix+10)
print("shape of matrix")
print(matrix.shape)
print("dimention of matrix")
print(matrix.ndim)